import { backGroundInfo, themeQuizMultipletForOpenAi } from "./interfaces";
import { backGroundProps } from "./interfaces";

export const backgroundsData: backGroundInfo[] = [
    {
      url: 'http://localhost:3000/background/1.mp4',
      durationInFps: 27120,
    },
    {
      url: 'http://localhost:3000/background/2.mp4',
      durationInFps: 7710,
    },
    {
      url: 'http://localhost:3000/background/3.mp4',
      durationInFps:  21150,
    },
    {
      url: 'http://localhost:3000/background/4.mp4',
      durationInFps: 15540,
    },
    {
      url: 'http://localhost:3000/background/5.mp4',
      durationInFps: 14550,
    },
    {
      url: 'http://localhost:3000/background/6.mp4',
      durationInFps: 7350,
    },
    {
        url: 'http://localhost:3000/background/7.mp4',
        durationInFps: 210,
      },
];

export const generateBackgroundProps = (backgroundData: backGroundInfo[]): backGroundProps => {
    const videoDuration = 1860;
    const randomIndex = Math.floor(Math.random() * backgroundData.length);
    const selectedBackground = backgroundData[randomIndex];
    let start;
    let end;
    if (videoDuration >=  selectedBackground.durationInFps)
    {
        start = 0;
        end = selectedBackground.durationInFps;
    }
    else {
        start = Math.floor(Math.random() * (selectedBackground.durationInFps - videoDuration));
        end = start + videoDuration;
    }
    return {
        url: selectedBackground.url,
        start: start,
        end: end
    };
};

export const themeQuizAffData = [
    {
        "theme": "Psychologie",
        "category": {
          "name": "Diagnostic et Compréhension Psychologique",
          "subCategory": [
            "Addiction au sucre",
            "Addiction au travail",
            "Addiction aux jeux vidéo",
            "Addiction au smartphone",
            "Addiction aux réseaux sociaux",
            "Addiction au tabac",
            "Addiction à la caféine",
            "Addiction pornographique",
            "Addiction à l'alcool",
            "Addiction aux drogues",
            "Addiction au cannabis",
            "Addiction au vapotage",
            "Dépendance affective",
            "Hypersexualité",
            "Trouble de l'usage de substances",
            "Trouble obsessionnel-compulsif (TOC)",
            "Dépression",
            "Troubles de l'humeur",
            "Anorexie",
            "Boulimie",
            "Phobies spécifiques",
            "Anxiété sociale",
            "Trouble panique",
            "Burnout étudiant",
            "Trouble de déficit de l'attention avec ou sans hyperactivité (TDAH)",
            "Troubles du sommeil",
            "Insomnie",
            "Somnolence excessive",
            "Gestion de l'image de soi",
            "Dysmorphophobie",
            "Estime de soi",
            "Auto-sabotage",
            "Procrastination",
            "Gestion du stress",
            "Résilience",
            "Intelligence émotionnelle",
            "Empathie",
            "Hypervigilance",
            "Sentiment d'isolement social",
            "Dépendance émotionnelle",
            "Trouble de l'adaptation",
            "Crises existentielles",
            "Syndrome de l'imposteur",
            "Sentiment de vide intérieur",
            "Automutilation",
            "Problèmes de communication interpersonnelle",
            "Anxiété de performance",
            "Culpabilité excessive",
            "Stress de l'enseignement supérieur",
            "Hyperconnexion",
            "Troubles d'apprentissage",
            "Troubles de l'audition sensorielle",
            "Surcharge cognitive",
            "Problèmes de concentration",
            "Attachement insécure",
            "Relations toxiques",
            "Comportements manipulateurs",
            "Peurs irrationnelles",
            "Régulation émotionnelle",
            "Sentiment d'abandon",
            "Épuisement émotionnel",
            "Ennui chronique",
            "Troubles de l'impulsion",
            "Comportements d'achat compulsif",
            "Séparation et divorce des parents",
            "Dilemmes moraux",
            "Incertitude et crainte de l'avenir",
            "Gestion des pertes et du deuil",
            "Comportements d'évasion",
            "Intériorisation des stéréotypes",
            "Influence des environnements toxiques",
            "Psychologie des peurs nocturnes",
            "Syndrome de Peter Pan",
            "Trouble du spectre autistique (TSA)",
            "Évolution des pratiques thérapeutiques modernes",
            "Stratégies d'affrontement et de coping",
            "Impact du réchauffement climatique",
            "Phénomène des influenceurs mentaux",
            "Exploration du moi profond",
            "Rôle des hormones dans l'humeur",
            "Adaptation aux changements de style de vie",
            "Effets de la musique sur l'humeur",
            "Régimes extrêmes",
            "Psychologie des microagressions",
            "Phénomène de la « Génération Sandwich »",
            "minimalisme",
            "Impact des médicaments sur la santé mentale",
            "Troubles bipolaires",
            "Psychologie de la gratitude",
            "Dépression saisonnière",
            "Trouble anxieux de séparation",
            "Psychologie des ambitions et du succès"
          ]
        }
      },
      {
        "theme": "Types de Personnalités et Traits de Caractère",
        "category": {
          "name": "Personnalités et Caractères",
          "subCategory": [
            "Amoureux de la nature",
            "Esprit aventurier",
            "Rêveur",
            "Philosophe",
            "Introverti",
            "Extraverti",
            "Perfectionniste",
            "Optimiste",
            "Pessimiste",
            "Hyperactif",
            "Calme",
            "Émotif",
            "Rationnel",
            "Empathique",
            "Cynique",
            "Altruiste",
            "Solitaire",
            "Curieux",
            "Créatif",
            "Innovateur",
            "Conservateur",
            "Révolutionnaire",
            "Pragmatique",
            "Visionnaire",
            "Organisé",
            "Spontané",
            "Indépendant",
            "Collaboratif",
            "Ambitieux",
            "Minimaliste",
            "Collecteur",
            "Discipliné",
            "Nonchalant",
            "Téméraire",
            "Prudent",
            "Sociable",
            "Discret",
            "Loyal",
            "Charismatique",
            "Manipulateur",
            "Autoritaire",
            "Conciliateur",
            "Sensible",
            "Résilient",
            "Obstiné",
            "Flexible",
            "Justicier",
            "Pacifiste",
            "Épicurien",
            "Ascète",
            "Spirituel",
            "Matérialiste",
            "Jovial",
            "Nostalgique",
            "Déterminé",
            "Facile à vivre",
            "Persévérant",
            "Détaché",
            "Médiateur",
            "Visionnaire",
            "Réfléchi",
            "Enthousiaste",
            "Sceptique",
            "Romantique",
            "Pragmatique",
            "Protecteur",
            "Insouciant",
            "Réfléchi",
            "Passionné",
            "Indifférent",
            "Galant",
            "Introspectif",
            "Indécis",
            "Fonceur",
            "Idéaliste",
            "Réaliste",
            "Humble",
            "Arrogant",
            "Tolérant",
            "Intransigeant",
            "Mélancolique",
            "Festif",
            "Taciturne",
            "Expressif",
            "Organisé",
            "Bordélique",
            "Économique",
            "Dépensier",
            "Gentil",
            "Naïf",
            "Protecteur",
            "Individualiste",
            "Collectif",
            "Responsable",
            "Inconséquent",
            "Audacieux",
            "Réservé",
            "Innovant",
            "Suiveur",
            "Charitable",
            "Avare",
            "Précautionneux",
            "Aventureux",
            "Perspicace",
            "Insatisfait",
            "Amical",
            "Renfermé",
            "Sage",
            "Têtu",
            "Serviable",
            "Dépendant",
            "Détaché",
            "Compliant",
            "Rebelle",
            "Discret",
            "Exubérant",
            "Grincheux",
            "Plein d'esprit",
            "Méfiante",
            "Confiant",
            "Extravagant",
            "Modeste",
            "Serein",
            "Anxieux",
            "Ordonné",
            "Chaotique",
            "Mélodramatique",
            "Stoïque",
            "Énigmatique",
            "Prévisible",
            "Gracieux",
            "Brusque",
            "Diplomate",
            "Franc",
            "Charmeur",
            "Direct",
            "Amoureux des animaux",
            "Technophile",
            "Écologique",
            "Spontané",
            "Planificateur",
            "Respectueux des règles",
            "Transgresseur",
            "Bienveillant",
            "Critique",
            "Patient",
            "Impulsif",
            "Rassurant",
            "Autoritaire",
            "Ouvert d'esprit",
            "Étroit d'esprit",
            "Fanatique",
            "Équilibré",
            "Contrôlant",
            "Encourageant",
            "Déstabilisant"
          ]
        }
      },
      {
        "theme": "Relations de Couple",
        "category": {
          "name": "Vie de Couple et Interactions Amoureuses",
          "subCategory": [
            "Romantique en amour",
            "Jaloux(se) en amour",
            "Indépendant(e) en amour",
            "Attentionné(e) en amour",
            "Avare en amour",
            "Aventurier/ère en amour",
            "Compliqué(e) en amour",
            "Supportif(ve) en amour",
            "Dragueur/se en amour",
            "Fusionnel(le) en amour",
            "Pragmatique en amour",
            "Émotif(ve) en amour",
            "Protecteur/trice en amour",
            "Distrait(e) en amour",
            "Communicatif(ve) en amour",
            "Pessimiste en amour",
            "Optimiste en amour",
            "Organisé(e) en amour",
            "Spontané(e) en amour",
            "Perfectionniste en amour",
            "Anxieux(se) en amour",
            "Rancunier/ère en amour",
            "Économe en amour",
            "Démonstratif(ve) en amour",
            "Réaliste en amour",
            "Philosophe en amour",
            "Empathique en amour",
            "Passionné(e) en amour",
            "Réservé(e) en amour",
            "Flexible en amour",
            "Impulsif(ve) en amour",
            "Routinier/ère en amour",
            "Rêveur/se en amour",
            "Courageux/se en amour",
            "Introverti(e) en amour",
            "Extraverti(e) en amour",
            "Loyal(e) en amour",
            "Provocateur/trice en amour",
            "Solitaire en amour",
            "Enthousiaste en amour",
            "Curieux/se en amour",
            "Généreux/se en amour",
            "Manipulateur/trice en amour",
            "Frustré(e) en amour",
            "Sensible en amour",
            "Calme en amour",
            "Ami(e) des animaux en amour",
            "Casanier/ère en amour",
            "Séducteur/trice en amour",
            "Perfectionniste en amour",
            "Équilibré(e) en amour"
          ]
        }
      },
]

export const themeQuizData : themeQuizMultipletForOpenAi[] = [  
  {
    "theme": "Culture Pop",
    "category": {
      "name": "Culture Pop",
      "subCategory": [
        // "Films Blockbusters",
        // "Films Indépendants",
        // "Films d'Animation",
        // "Sagas Cinématographiques (ex: Star Wars, Harry Potter)",
        // "Films de Super-Héros (Marvel, DC)",
        // "Films d'Horreur",
        // "Comédies Romantiques",
        // "Films des Années 80",
        // "Films des Années 90",
        // "Films des Années 2000",
        // "Films d'Action",
        // "Documentaires Célèbres",
        // "Personnages de Films Iconiques",
        // "Séries TV Culte (Friends, Breaking Bad, etc.)",
        // "Séries Netflix",
        // "Séries HBO",
        // "Séries Animées (Rick et Morty, Les Simpson)",
        // "Séries Coréennes (K-Dramas)",
        // "Séries des Années 80-90 (Buffy, X-Files)",
        // "Anime (Dragon Ball, Naruto, My Hero Academia)",
        // "Manga (One Piece, Attack on Titan)",
        // "Culture Geek (Comics, Jeux Vidéo, Science-fiction)",
        // "Jeux Vidéo (classiques, contemporains)",
        // "Jeux Vidéo Rétro (années 80-90)",
        // "Jeux Vidéo RPG (Final Fantasy, The Witcher)",
        // "Jeux Vidéo FPS (Call of Duty, Halo)",
        // "Esports (League of Legends, Fortnite)",
        // "Influenceurs et Youtubeurs Célèbres",
        // "Mèmes Internet",
        // "Buzz Internet et Challenges Viraux",
        // "Culture Emo et Punk des Années 2000",
        // "Musique Pop des Années 2000 (Britney Spears, NSYNC)",
        // "Musique Rap/Hip-Hop",
        // "Groupes de Rock Célèbres",
        // "Icônes de la Pop Culture (Beyoncé, Michael Jackson)",
        // "Artistes Pop Actuels (Billie Eilish, Taylor Swift)",
        // "Musique Électronique (Daft Punk, Calvin Harris)",
        // "Boy Bands et Girl Bands (Backstreet Boys, Spice Girls)",
        // "Dessins Animés Nostalgie (Sailor Moon, Scooby-Doo)",
        // "Comédies Cultes (How I Met Your Mother, The Office)",
        // "Reality TV (Kardashians, Love Island)",
        // "Superstars du Sport (Michael Jordan, Serena Williams)",
        // "Histoires de Jeux de Société Populaires (Monopoly, Trivial Pursuit)",
        // "Tendances Mode Célèbres (des Années 80 à aujourd'hui)",
        // "Collections de Jouets Nostalgie (Lego, Barbie)",
        // "Objets de Collection (Funko Pop, Cartes Pokémon)",
        // "Littérature Populaire (Harry Potter, Hunger Games)",
        // "BD et Comics Célèbres (Marvel, DC, Astérix)",
        // "Personnages Disney et Pixar",
        // "Monde des Super-Héros (Marvel, DC)",
        // "Cinéma d'Animation Japonais (Ghibli, Akira)",
        // "Icônes de Mode Pop (Rihanna, Kanye West)",
        // "Culture Cosplay",
        // "Streamers Twitch et Créateurs de Contenu",
        // "Festivals de Musique Pop (Coachella, Tomorrowland)",
        // "Spectacles de Stand-up et Comédie (Kevin Hart, Dave Chappelle)",
        // "Culture Drag (RuPaul's Drag Race)",
        // "Stars de la Télé-Réalité (Kardashians, Bachelor)",
        // "Tendances Récents de la Mode TikTok",
        // "Influenceurs Instagram",
        // "Personnages de Jeux Vidéo Iconiques (Mario, Lara Croft)",
        // "Événements Célébrés dans la Pop Culture (Comic-Con, E3)",
        // "Coutumes et Habitudes des Fandoms (Harry Potter, Star Trek)",
        // "Théories du Complot Pop Culture (Area 51, Elvis est vivant)",
        // "Histoires Urbaines et Légendes Pop Culture",
        // "Films Cultes des Années 70 (Star Wars, Le Parrain)",
        // "Films de Science-Fiction (Blade Runner, Dune)",
        // "Films Basés sur des Faits Réels",
        // "Réalisateurs Célèbres (Spielberg, Tarantino)",
        // "Films de Bollywood",
        // "Musicals (La La Land, Hamilton)",
        // "Films d'Art Martiaux (Bruce Lee, Jackie Chan)",
        // "Films de Noël Célèbres (Home Alone, Elf)",
        // "Séries TV Anticipation (Black Mirror, The Twilight Zone)",
        // "Sitcoms Célèbres des Années 90 (Seinfeld, Friends)",
        // "Séries Documentaires (Tiger King, Making a Murderer)",
        // "Séries Historiques (The Crown, Vikings)",
        // "Adaptations Littéraires en Séries TV (Game of Thrones, The Witcher)",
        // "Personnages de Séries TV Iconiques (Walter White, Daenerys Targaryen)",
        // "Personnages de Comics Célèbres (Spider-Man, Batman)",
        // "Nostalgie des Années 90 (Pokémon, Tamagotchi)",
        // "Nostalgie des Années 2000 (Myspace, MP3 Players)",
        // "Dessin Animé des Années 90 (Les Tortues Ninja, Les Razmoket)",
        // "Culture Punk Rock (Green Day, Blink-182)",
        // "Musique Indie (Arctic Monkeys, Tame Impala)",
        // "Musique Grunge (Nirvana, Pearl Jam)",
        // "Musique Pop Punk (Paramore, Fall Out Boy)",
        // "Artistes Hip-Hop des Années 90 (Tupac, Notorious B.I.G.)",
        // "Chansons Virales d'Internet (Gangnam Style, Harlem Shake)",
        // "Stars de la Pop Culture des Années 80 (Madonna, Prince)",
        // "Icônes de la Culture Hip-Hop Moderne (Drake, Kendrick Lamar)",
        // "Tendances Make-Up sur YouTube (Beauty Gurus, Tutorials)",
        // "Mode des Années 2000 (Denim, Juicy Couture)",
        // "Culture Gothique (Marilyn Manson, The Cure)",
        // "Culture Nerd (Donjons & Dragons, Star Trek)",
        // "Figurines de Collection (Star Wars, Transformers)",
        // "Films Cultes d'Horreur (Halloween, Scream)",
        // "Films d'Auteurs Contemporains (Wes Anderson, Denis Villeneuve)",
        // "Adaptations en Films de Comics (Marvel Cinematic Universe, DC Extended Universe)",
        // "Fan Theories Populaires (Avengers, Stranger Things)",
        // "Célébrités Virales d'Internet (Charli D'Amelio, PewDiePie)",
        // "Sagas Littéraires Modernes (Twilight, Divergent)",
        // "Art Urbain et Street Art (Banksy, Shepard Fairey)",
        // "Films Sur le Sport (Rocky, Remember the Titans)",
        // "Culture des Festivals de Films (Cannes, Sundance)",
        // "Jeux Vidéo Open World (GTA, The Legend of Zelda: Breath of the Wild)",
        // "Jeux Vidéo de Combat (Street Fighter, Mortal Kombat)",
        // "Émissions TV Cultes (Who Wants to Be a Millionaire?, Survivor)",
        // "Télévision des Années 80 (Miami Vice, Magnum)",
        // "Films Crossover (Avengers, Justice League)",
        // "Films d'Espionnage (James Bond, Jason Bourne)",
        // "Musique Alternative des Années 80-90 (The Smiths, Radiohead)",
        // "Festivals de Pop Culture (San Diego Comic-Con, PAX)",
        // "Twitch Rivals et Compétitions Esports",
        // "Podcasts Populaires (Serial, The Joe Rogan Experience)",
        // "Documentaires Musicaux (Amy, What Happened, Miss Simone?)",
        // "Films Cultes de la Blaxploitation (Shaft, Superfly)",
        // "Nostalgie des Jeux de Cartes (Yu-Gi-Oh!, Magic: The Gathering)",
        // "Jouets Iconiques des Années 80 (He-Man, My Little Pony)",
        // "Télénovelas (Betty la Fea, Rubí)",
        // "Reality Shows Musicaux (The Voice, American Idol)",
        // "Dessins Animés des Années 2000 (Ben 10, Kim Possible)",
        // "Webtoons et Bandes Dessinées en Ligne",
        // "Monde des Figurines Pop Vinyl",
        // "Jeux Vidéo Indépendants (Undertale, Hollow Knight)",
        // "Icônes de la Mode Pop des Années 2010 (Kanye West, Kim Kardashian)",
        // "Événements Mémorables de la Pop Culture (Concert de Live Aid, Super Bowl Halftime Shows)",
        // "Phénomènes de Mode (Ugg Boots, Skinny Jeans)",
        // "Évolutions Technologiques dans la Pop Culture (iPod, Snapchat Spectacles)",
        // "Célébrités Enfants des Années 90 et 2000 (Macaulay Culkin, Lindsay Lohan)",
        // "Humoristes et Satiristes Populaires (John Oliver, Trevor Noah)",
        // "Séries True Crime",
        // "Séries Antiques et Historiques (Downton Abbey, The Tudors)",
        // "Séries Comiques Animées pour Adultes (Family Guy, South Park)",
        // "Séries d'Aventures (Stranger Things, Lost)",
        // "Séries Post-Apocalyptiques (The Walking Dead, The 100)",
        // "Comédies pour Ados (Glee, Gossip Girl)",
        // "Séries sur les Super-Héros (Arrow, The Flash)",
        // "Films Basés sur des Jeux Vidéo (Mortal Kombat, Sonic)",
        // "Films Catastrophes (Armageddon, 2012)",
        // "Films sur les Voyages dans le Temps (Retour vers le Futur, Interstellar)",
        // "Films Cultes des Années 60 (Psycho, 2001: L'Odyssée de l'Espace)",
        // "Films de Kung Fu (Ip Man, The Raid)",
        // "Sagas d'Aventure Épique (Indiana Jones, Le Seigneur des Anneaux)",
        // "Films Basés sur des Musicals (Les Misérables, Chicago)",
        // "Cinéma de Super-Héros Non-Américain (Super Lopez, The Great Yokai War)",
        // "Acteurs et Actrices Iconiques (Meryl Streep, Leonardo DiCaprio)",
        // "Scandales d'Hollywood",
        // "Films de Zombies (World War Z, Shaun of the Dead)",
        // "Films de Comédie Noire (Pulp Fiction, Fargo)",
        // "Films Psychologiques (Inception, Shutter Island)",
        // "Célébrités des Réseaux Sociaux (Addison Rae, Bella Poarch)",
        // "Émissions TV Cultes des Années 70 (M*A*S*H, The Brady Bunch)",
        // "Sitcoms Modernes (Brooklyn Nine-Nine, Parks and Recreation)",
        // "Héros de la Science-Fiction (Doctor Who, Captain Kirk)",
        // "Influence des Mangas et Animes dans la Pop Culture",
        // "Jeux Vidéo Basés sur des Films (GoldenEye 007, Spider-Man)",
        // "Personnages Fictifs de Cultures Étrangères (Totoro, Lupin III)",
        // "Films Indiens Hors Bollywood (The Lunchbox, Gangs of Wasseypur)",
        // "Films Documentaires sur la Nature (Our Planet, March of the Penguins)",
        // "Pop Culture des Années 50 (Grease, James Dean)",
        // "Émissions TV de Compétition (The Amazing Race, Top Chef)",
        // "Vidéos Virales de YouTube (Charlie Bit My Finger, Double Rainbow)",
        // "Humoristes de Stand-Up Iconiques (Richard Pryor, Eddie Murphy)",
        // "Stars de TikTok et Vine",
        // "Influence de la K-Pop (BTS, BLACKPINK)",
        // "Films d'Auteurs Asiatiques (Parasite, Oldboy)",
        // "Cinéma Latino-Américain (Y Tu Mamá También, Amores Perros)",
        // "Cinéma Africain (Nollywood, The Boy Who Harnessed the Wind)",
        // "Films sur les Voyages dans l'Espace (Gravity, The Martian)",
        // "Films de Vampires (Twilight, Dracula)",
        // "Films d'Anthologie (V/H/S, Black Mirror: Bandersnatch)",
        // "Séries TV Basées sur des Jeux Vidéo (The Witcher, Castlevania)",
        // "Livestreams et Contenus en Direct (Mixer, IRL Streams)",
        // "Documentaires sur les Célébrités (Miss Americana, The Last Dance)",
        // "Influence de la Mode Streetwear (Supreme, Off-White)",
        // "Photographie de Mode et de Pop Culture (Annie Leibovitz, Helmut Newton)",
        // "Collections de Sneakers et de Chaussures Iconiques (Air Jordan, Yeezy)",
        // "Produits Dérivés Célèbres (T-shirts de Groupes, Merchandising Pop Culture)",
        // "Événements Cross-Médias (Fortnite Concerts, Travis Scott)",
        // "Événements de Lancements de Produits Technologiques (Apple Keynotes, E3)",
        // "Influenceurs de Fitness et de Style de Vie",
        // "Pop Culture des Jeux de Rôle (Critical Role, Dimension 20)",
        // "Influence des Séries d'Anthologie (American Horror Story, Black Mirror)",
        // "Fandoms de Fiction Science-Fiction (Star Trek, Doctor Who)",
        // "Culture Pop Geek (Comic Books, Geek Chic)",
        // "Icônes des Films Muets (Charlie Chaplin, Buster Keaton)",
        // "Films Basés sur des Pièces de Théâtre (Hamlet, Un Tramway nommé Désir)",
        // "Influence des Vidéoclips Musicaux (Thriller, Bad Romance)",
        // "Films sur la Musique et les Musiciens (Bohemian Rhapsody, Rocketman)",
        // "Films de Héros Féminins (Wonder Woman, Mad Max: Fury Road)",
        // "Artistes Visuels Pop (Andy Warhol, Keith Haring)",
        // "Influence de la Musique Country (Taylor Swift, Dolly Parton)",
        // "Sports Extrêmes dans la Pop Culture (Tony Hawk, X Games)",
        // "Icônes du Cinéma d'Art et Essai",
        // "Tendances Beauté et Soins de la Peau",
        // "Influence des Jeux de Société Modernes (Catan, Pandemic)",
        // "Phénomènes de Mode Virale (Ice Bucket Challenge, Mannequin Challenge)",
        // "Collections de Vinyl et Culture de la Musique Analogique",
        // "Influence de la Culture des Skateboards (Tony Hawk, Streetwear)",
        // "Influence des Supermodels (Naomi Campbell, Gigi Hadid)",
        // "Féminisme et Pop Culture",
        // "Films LGBTQ+ (Moonlight, Call Me By Your Name)",
        // "Télévision Britannique Culte (Doctor Who, Sherlock)",
        // "Influence des Telenovelas sur la Pop Culture",
        // "Films d'Animation Non Américains (Le Tombeau des Lucioles, La Tortue Rouge)",
        // "Pop Culture Scandinave (Nordic Noir, Vikings)",
        // "Culture de la Musique Lo-Fi et Chillhop",
        // "Tendances Décoration Intérieure Pop (IKEA, Mid-Century Modern)",
        // "Influence des Techno-thrillers (Mr. Robot, Ex Machina)",
        // "Horreur Psychologique dans la Pop Culture (Hérédité, Get Out)",
        // "Franchises Célébrant les Anniversaires (James Bond 50 ans, Mario 35 ans)",
        // "Influence des Web Séries (The Guild, Red vs. Blue)",
        // "Films d'Auteurs Européens (Pedro Almodóvar, Lars von Trier)",
        // "Films de Gangsters (Le Parrain, Les Affranchis)",
        // "Séries TV Canadiennes (Schitt's Creek, Degrassi)",
        // "Films sur les Super Espions (Kingsman, Spy Kids)",
        // "Adaptations de Comics en Animé (Batman: The Animated Series, Invincible)",
        // "Séries TV de Science-Fiction Britanniques (Doctor Who, Black Mirror)",
        // "Célébrités du Stand-Up des Années 2000 (Kevin Hart, Amy Schumer)",
        // "Influence des Soundtracks dans la Pop Culture (Hans Zimmer, John Williams)",
        // "Films de Noël Alternatifs (Die Hard, Gremlins)",
        // "Culture DIY (Pinterest, Etsy)",
        // "Séries TV Documentaires Animaux (Planet Earth, Tiger King)",
        // "Webcomics Populaires (xkcd, The Oatmeal)",
        // "Influence des Covers Musicaux sur YouTube",
        // "Films Biographiques Sportifs (Rudy, Invincible)",
        // "Films et Séries sur le Surf (Blue Crush, Point Break)",
        // "Émissions Culinaires (Top Chef, MasterChef)",
        // "Phénomène des Concerts en Streaming",
        // "Films de Robots et d'Intelligence Artificielle (Ex Machina, Chappie)",
        // "Comédies Musicales Modernes (The Greatest Showman, Mamma Mia!)",
        // "Influence de la Photographie Instagram (Food Photography, Travel Influencers)",
        // "Monde des Figurines Art Toys (Kidrobot, KAWS)",
        // "Mèmes Basés sur des Films et Séries TV (Disaster Girl, Distracted Boyfriend)",
        // "Héros d'Action des Années 80 (Sylvester Stallone, Arnold Schwarzenegger)",
        // "Culture de la Réparation et de l'Upcycling",
        // "Films et Séries sur l'Espace (Interstellar, Gravity)",
        // "Influence des Séries de Vampires (True Blood, The Vampire Diaries)",
        // "Sous-cultures de la Musique Punk (Crust Punk, Hardcore Punk)",
        // "Séries TV de Mystère (Sherlock, True Detective)",
        // "Crossover de Séries TV (Crisis on Infinite Earths, Chicago Fire/PD/Med)",
        // "Phénomènes d'Unboxing sur YouTube",
        // "Célébrités de la Radio et des Podcasts (Howard Stern, Marc Maron)",
        // "Tendances Fitness sur Instagram (CrossFit, Yoga Challenges)",
        // "Influence des Défilés de Mode (Victoria's Secret Fashion Show, Paris Fashion Week)",
        // "Films sur la Guerre Froide (Le Pont des Espions, The Manchurian Candidate)",
        // "Séries TV sur le Monde Politique (House of Cards, The West Wing)",
        // "Séries TV Basées sur des Livres Jeunesse (A Series of Unfortunate Events, Anne with an E)",
        // "Culture du Streaming Musical (Spotify, Apple Music)",
        // "Influence des Chorégraphes de Danse (Martha Graham, Pina Bausch)",
        // "Tendances de Décoration Minimaliste",
        // "Films sur la Musique Jazz (Whiplash, La La Land)",
        // "Artistes Pop Art Contemporains (Takashi Murakami, Yayoi Kusama)",
        // "Séries TV sur les Relations Familiales (This Is Us, Parenthood)",
        // "Influence des Bandes Originales de Films sur la Mode (Drive, Clueless)",
        // "Films de Monstres (Godzilla, King Kong)",
        // "Influence des Studios d'Animation (Pixar, Laika)",
        // "Culture du Skateboard dans le Cinéma (Mid90s, Lords of Dogtown)",
        // "Personnages de Bandes Dessinées Franco-Belges (Tintin, Lucky Luke)",
        // "Célébrités Influentes des Années 2010 (Kylie Jenner, Ariana Grande)",
        // "Influence des Films Indépendants à Petit Budget (Paranormal Activity, Blair Witch Project)",
        // "Films d'Aventures en Haute Mer (Pirates des Caraïbes, Master and Commander)",
        // "Horreur Cosmique dans le Cinéma (The Thing, Color Out of Space)",
        // "Films et Séries sur les Sociétés Secrètes (Eyes Wide Shut, The Da Vinci Code)",
        // "Influence des Chaînes de Cuisine YouTube (Binging with Babish, Tasty)",
        // "Célébrités Influentes de la Tech (Elon Musk, Steve Jobs)",
        // "Jeux Vidéo Basés sur des Animes (Dragon Ball Z: Kakarot, Naruto: Ultimate Ninja Storm)",
        // "Influence des Thématiques Apocalyptiques (Mad Max, The Road)",
        // "Jeux Vidéo Survie (The Forest, Don't Starve)",
        // "Films et Séries sur les Dystopies (Hunger Games, Blade Runner)",
        // "Influence des Festivals d'Art Numérique (Burning Man, SXSW Interactive)",
        // "Culture du Café dans la Pop Culture (Friends, Gilmore Girls)",
        // "Influence des Marques de Mode Streetwear (Bape, Supreme)",
        // "Influence des Groupes de Musique Virtuels (Gorillaz, Hatsune Miku)",
        // "Films sur le Monde de la Télévision (The Truman Show, Broadcast News)",
        // "Séries TV sur les Voyages Temporels (Dark, Timeless)",
        // "Influence des Musées Virtuels et Expositions Digitales",
        // "Phénomènes de Reboot et de Remakes au Cinéma",
        // "Séries TV Inspirées par des Histoires Vraies (Narcos, Chernobyl)",
        // "Films de Famille et Enfants Cultes (E.T., Jumanji)",
        // "Influence des Skits Comiques sur YouTube (Smosh, Key & Peele)",
        // "Influence des Réseaux Sociaux sur les Tendances de Mode (TikTok Fashion Trends)",
        // "Films et Séries sur les Assassins et Tueurs à Gages (John Wick, Léon)",
        // "Influence des Architectes Modernes sur le Design Pop (Zaha Hadid, Frank Gehry)",
        // "Influence des Effets Spéciaux et CGI dans les Films",
        // "Pop Culture des Années 40 (Casablanca, Frank Sinatra)",
        // "Phénomènes de Revival dans la Pop Culture (Stranger Things et la Nostalgie des Années 80)",
        // "Films Basés sur des Mythologies Anciennes (Thor, Percy Jackson)",
        // "Séries TV sur les Sciences (Breaking Bad, The Big Bang Theory)",
        // "Films et Séries Basés sur des Journaux Intimes (Bridget Jones, Anne Frank)",
        // "Influence des Musées Pop-Up et Expériences Immersives (Museum of Ice Cream, Color Factory)"
        "Films Blockbusters",
        "Films Indépendants",
        "Films d'Animation",
        "Sagas Cinématographiques (ex: Star Wars, Harry Potter)",
        "Films de Super-Héros (Marvel, DC)",
        "Films d'Horreur",
        "Comédies Romantiques",
        "Films des Années 80",
        "Films des Années 90",
        "Films des Années 2000",
        "Films d'Action",
        "Documentaires Célèbres",
        "Personnages de Films Iconiques",
        "Séries TV Culte (Friends, Breaking Bad, etc.)",
        "Séries Netflix",
        "Séries HBO",
        "Séries Animées (Rick et Morty, Les Simpson)",
        "Séries Coréennes (K-Dramas)",
        "Séries des Années 80-90 (Buffy, X-Files)",
        "Anime (Dragon Ball, Naruto, My Hero Academia)",
        "Manga (One Piece, Attack on Titan)",
        "Culture Geek (Comics, Jeux Vidéo, Science-fiction)",
        "Jeux Vidéo (classiques, contemporains)",
        "Jeux Vidéo Rétro (années 80-90)",
        "Jeux Vidéo RPG (Final Fantasy, The Witcher)",
        "Jeux Vidéo FPS (Call of Duty, Halo)",
        "Esports (League of Legends, Fortnite)",
        "Influenceurs et Youtubeurs Célèbres",
        "Mèmes Internet",
        "Buzz Internet et Challenges Viraux",
        "Culture Emo et Punk des Années 2000",
        "Musique Pop des Années 2000 (Britney Spears, NSYNC)",
        "Musique Rap/Hip-Hop",
        "Groupes de Rock Célèbres",
        "Icônes de la Pop Culture (Beyoncé, Michael Jackson)",
        "Artistes Pop Actuels (Billie Eilish, Taylor Swift)",
        "Musique Électronique (Daft Punk, Calvin Harris)",
        "Boy Bands et Girl Bands (Backstreet Boys, Spice Girls)",
        "Dessins Animés Nostalgie (Sailor Moon, Scooby-Doo)",
        "Comédies Cultes (How I Met Your Mother, The Office)",
        "Reality TV (Kardashians, Love Island)",
        "Superstars du Sport (Michael Jordan, Serena Williams)",
        "Histoires de Jeux de Société Populaires (Monopoly, Trivial Pursuit)",
        "Tendances Mode Célèbres (des Années 80 à aujourd'hui)",
        "Collections de Jouets Nostalgie (Lego, Barbie)",
        "Objets de Collection (Funko Pop, Cartes Pokémon)",
        "Littérature Populaire (Harry Potter, Hunger Games)",
        "BD et Comics Célèbres (Marvel, DC, Astérix)",
        "Personnages Disney et Pixar",
        "Monde des Super-Héros (Marvel, DC)",
        "Cinéma d'Animation Japonais (Ghibli, Akira)",
        "Icônes de Mode Pop (Rihanna, Kanye West)",
        "Culture Cosplay",
        "Streamers Twitch et Créateurs de Contenu",
        "Festivals de Musique Pop (Coachella, Tomorrowland)",
        "Spectacles de Stand-up et Comédie (Kevin Hart, Dave Chappelle)",
        "Culture Drag (RuPaul's Drag Race)",
        "Stars de la Télé-Réalité (Kardashians, Bachelor)",
        "Tendances Récents de la Mode TikTok",
        "Influenceurs Instagram",
        "Personnages de Jeux Vidéo Iconiques (Mario, Lara Croft)",
        "Événements Célébrés dans la Pop Culture (Comic-Con, E3)",
        "Coutumes et Habitudes des Fandoms (Harry Potter, Star Trek)",
        "Théories du Complot Pop Culture (Area 51, Elvis est vivant)",
        "Histoires Urbaines et Légendes Pop Culture",
        "Films Cultes des Années 70 (Star Wars, Le Parrain)",
        "Films de Science-Fiction (Blade Runner, Dune)",
        "Films Basés sur des Faits Réels",
        "Réalisateurs Célèbres (Spielberg, Tarantino)",
        "Films de Bollywood",
        "Musicals (La La Land, Hamilton)",
        "Films d'Art Martiaux (Bruce Lee, Jackie Chan)",
        "Films de Noël Célèbres (Home Alone, Elf)",
        "Séries TV Anticipation (Black Mirror, The Twilight Zone)",
        "Sitcoms Célèbres des Années 90 (Seinfeld, Friends)",
        "Séries Documentaires (Tiger King, Making a Murderer)",
        "Séries Historiques (The Crown, Vikings)",
        "Adaptations Littéraires en Séries TV (Game of Thrones, The Witcher)",
        "Personnages de Séries TV Iconiques (Walter White, Daenerys Targaryen)",
        "Personnages de Comics Célèbres (Spider-Man, Batman)",
        "Nostalgie des Années 90 (Pokémon, Tamagotchi)",
        "Nostalgie des Années 2000 (Myspace, MP3 Players)",
        "Dessin Animé des Années 90 (Les Tortues Ninja, Les Razmoket)",
        "Culture Punk Rock (Green Day, Blink-182)",
        "Musique Indie (Arctic Monkeys, Tame Impala)",
        "Musique Grunge (Nirvana, Pearl Jam)",
        "Musique Pop Punk (Paramore, Fall Out Boy)",
        "Artistes Hip-Hop des Années 90 (Tupac, Notorious B.I.G.)",
        "Chansons Virales d'Internet (Gangnam Style, Harlem Shake)",
        "Trend TIKTOK"

      ]
    }
  },     
    {
      theme: "Mystères et Enigmes",
      category : {
        name : "Enigmes et Phénomènes Mystérieux",
        subCategory : [
          "Disparitions Mystérieuses, Phénomènes Paranormaux, Casse-Têtes Logiques",
          "Lieux Hantés, Secrets de l'Univers, Conspirations Célèbres",
          "Créatures Légendaires, Signes et Symboles Énigmatiques, Merveilles de l'Antiquité",
          "Codes et Cryptographies, Mystères de l'Égypte Ancienne, Incidents Inexpliqués",
          "Objets Volants Non Identifiés, Prédictions et Prophéties, Mystères de la Mer",
          "Disparition de Civilisations, Forêts Interdites, Apparitions Fantomatiques",
          "Phénomènes Psychiques, Monuments et Alignements Mystérieux, Énigmes Mathématiques Célèbres",
          "Expériences Surnaturelles, Zones et Portails Étranges, Messages Cachés dans l'Art",
          "Énigmes Littéraires, Lieux Sacrés et Magiques, Pouvoirs de la Nature",
          "Objets et Artefacts Maudits, Expéditions Disparues, Histoires de Malédictions",
          "Théories de la Conspiration, Symboles Mystiques, Légendes Urbaines",
          "Paranormal et Science, Mystères du Cosmos, Enigmes de la Nature",
          "Phénomènes Atmosphériques Étranges, Choses Inexplicables de l'Histoire, Expériences Étranges",
          "Histoires et Légendes Étranges, Objets Mystérieux Découverts, Mystères Non Résolus",
          "Influences Étranges sur la Société, Paradoxes Mystérieux, Croyances et Superstitions",
        ]
      }
    },    
    {
      "theme": "Animaux et Nature",
      "category": {
        "name": "Aventures Animales",
        "subCategory": [
          "Animaux Sauvages, Espèces en Danger, Superpouvoirs Animaliers",
          "Forêts et Océans, Mythes Animaliers, Animaux Domestiques Étonnants",
          "Relations Homme-Animal, Conservation de la Faune, Biologie Marine",
          "Créatures des Profondeurs, Écosystèmes Exotiques, Survie dans la Nature",
          "Comportements Étonnants, Techniques de Chasse et Prédation, Biodiversité en Forêt Tropicale",
          "Oiseaux Migrateurs, Curiosités du Règne Animal, Adaptations Évolutives",
          "Espèces Invasives, Animaux dans l'Histoire, Monstres Marins",
          "Histoires de Sauvetages Animaliers, Faune et Flore des Régions Polaires, Les Grands Prédateurs",
          "Éthologie et Cognition Animale, Pollinisation et Écosystèmes, Mystères de la Faune Australienne",
          "Rituels Animaliers, Animaux dans les Mythologies, Espèces Récemment Découvertes",
          "Bêtes Légendaires, Les Plus Grands Records du Règne Animal, Communication Animale",
          "Migration et Nomadisme Animal, Écosystèmes de Montagne, Comportements de Nuit",
          "Animaux et Changements Climatiques, Habitats Urbains des Animaux, Espèces Menacées par l'Homme",
          "Interactions entre Espèces, Animaux et Technologies, Animaux dans les Arts",
          "Survivalisme et Faune, Influence des Animaux sur la Culture Humaine, Éducation à la Faune",
          "Reproduction et Développement Animal, Relations Symbiotiques, Animaux dans les Religions",
        ]
      },
    },    
    {
      "theme": "Héros et Légendes",
      "category": {
        "name": "Personnages Héroïques",
        "subCategory": [
          "Héros des Mythes Grecs et Romains",
          "Légendes des Arts Martiaux (Bruce Lee, Miyamoto Musashi)",
          "Figures de la Révolution Américaine (George Washington, Paul Revere)",
          "Héros de la Résistance Française (Jean Moulin, Lucie Aubrac)",
          "Figures Héroïques des Contes Africains",
          "Personnages Célèbres du Monde Arabe (Saladin, Ibn Battuta)",
          "Héros de la Mythologie Slave (Perun, Vasilisa la Sage)",
          "Rois et Reines Mythiques (Roi Arthur, Cléopâtre)",
          "Héros de l'Épopée de Gilgamesh",
          "Figures Célèbres de la Mythologie Nord-Amérindienne",
          "Explorateurs Célèbres des Temps Modernes (Neil Armstrong, Jacques Cousteau)",
          "Légendes des Vikings et des Sagas Nordiques (Ragnar Lothbrok, Leif Erikson)",
          "Figures de l'Indépendance Indienne (Gandhi, Subhas Chandra Bose)",
          "Samouraïs Légendaires (Oda Nobunaga, Tomoe Gozen)",
          "Héros du Cinéma d'Aventure (Indiana Jones, Lara Croft)",
          "Personnages Héroïques des Films d'Animation (Mulan, Simba)",
          "Légendes du Moyen-Orient (Sinbad, Aladin)",
          "Figures de la Renaissance Européenne (Léonard de Vinci, Michel-Ange)",
          "Figures Mythologiques Polynésiennes (Māui, Pele)",
          "Explorateurs de l'Arctique et de l'Antarctique (Roald Amundsen, Ernest Shackleton)",
          "Légendes de la Grèce Antique (Achille, Ulysse)",
          "Personnages des Légendes Celtiques (Cúchulainn, Fionn mac Cumhaill)",
          "Héros et Anti-Héros de la Mythologie Hindoue (Rama, Ravana)",
          "Figures de la Révolution Française (Napoléon Bonaparte, Jeanne d'Arc)",
          "Guerriers de la Chine Ancienne (Sun Tzu, Hua Mulan)",
          "Figures des Grandes Explorations (Marco Polo, Ferdinand Magellan)",
          "Personnages Légendaires des Récits Allemands (Faust, Siegfried)",
          "Héros de la Conquête du Nouveau Monde (Hernán Cortés, Francisco Pizarro)",
          "Légendes de la Mythologie Inuit (Sedna, Nanook)",
          "Héros du Mouvement des Droits Civiques (Martin Luther King Jr., Rosa Parks)",
          "Figures Mythologiques Japonaises (Amaterasu, Susanoo)",
          "Figures Héroïques de l'Histoire Scandinave (Harald à la Belle Chevelure, Eric le Rouge)",
          "Héros de la Renaissance Italienne (Galilée, Machiavel)",
          "Figures Héroïques des Grandes Guerres (Winston Churchill, Charles de Gaulle)",
          "Légendes de la Lutte Contre l'Apartheid (Nelson Mandela, Desmond Tutu)",
          "Figures Mythologiques de la Mésopotamie (Enki, Ishtar)",
          "Personnages Héroïques des Contes Russes (Baba Yaga, Ilya Mouromets)",
          "Héros des Sagas Épiques Indiennes (Arjuna, Karna)",
          "Figures de la Guerre d'Indépendance du Mexique (Miguel Hidalgo, José María Morelos)",
          "Personnages Héroïques de la Mythologie Aztèque (Quetzalcoatl, Huitzilopochtli)",
          "Figures de la Guerre de Sécession Américaine (Robert E. Lee, Ulysses S. Grant)",
          "Héros de la Mythologie Perse (Rostam, Zahhak)",
          "Figures Héroïques de la Révolution Russe (Lénine, Trotsky)",
          "Légendes des Tribus Aborigènes (Le Serpent Arc-en-ciel, Bunjil)",
          "Personnages Célèbres de l'Âge de Bronze (Gilgamesh, Sargon d'Akkad)",
          "Figures Héroïques de la Guerre du Vietnam (Ho Chi Minh, Võ Nguyên Giáp)",
          "Légendes de l'Afrique du Nord (Hannibal, Jugurtha)",
          "Héros et Anti-Héros des Contes de Fées (Barbe Bleue, Cendrillon)",
          "Figures Héroïques du Cinéma de Science-Fiction (Luke Skywalker, Ellen Ripley)",
          "Légendes de la Mythologie Maya (Kukulkan, Chaac)",
          "Figures Héroïques de l'Histoire Médiévale (Richard Cœur de Lion, Gengis Khan)",
          "Héros des Temps Modernes (Malala Yousafzai, Greta Thunberg)",
          "Figures Mythologiques des Andes (Viracocha, Pachamama)",
          "Héros des Contes et Légendes Scandinaves (Beowulf, Harald Hardrada)"
        ]
      }
    },    
    {
      "theme": "Couple et Relation Amoureuse",
      "category": {
        "name": "Toutes les Facettes de la Vie de Couple",
        "subCategory": [
          // "Premières Rencontres, Moments Romantiques Mémorables, Idées de Rendez-vous Créatifs",
          // "Romances Littéraires, Amour au Cinéma, Symboles Romantiques, Cadeaux de l'Amour",
          // "Secrets d'un Amour Éternel, Lettres d'Amour Épiques, Musique de Romance",
          // "Célébrations Romantiques du Monde, Gestes Romantiques Inattendus, Traditions de Mariage Uniques",
          // "Les Grands Romantiques de l'Histoire, Langage de l'Amour, Techniques de Communication Positive",
          // "Les 5 Langages de l'Amour, Conflits et Résolution, Jeux de Communication, Écoute Active en Couple",
          // "Comprendre les Signaux Non-Verbaux, Empathie et Complicité, Comment Exprimer ses Sentiments",
          // "Secrets de la Communication Émotionnelle, Valeurs Communes et Divergences, Les Questions Importantes à Poser",
          // "Décryptage des Gestes d'Affection, Thérapie de Couple, Différences Culturelles et Communication",
          // "Gérer la Distance et l'Éloignement, Les Épreuves de la Vie à Deux, Défis de la Vie Moderne",
          // "Gérer les Finances en Couple, Travail et Vie Personnelle, Gérer les Changements Majeurs",
          // "Rebondir Après une Dispute, Les Défis de la Parentalité, Se Soutenir en Temps de Crise",
          // "Inquiétudes et Jalousie, Intimité et Stress, Vie de Couple pendant la Pandémie",
          // "Les Secrets de la Patience, Dépendance et Indépendance, Surmonter les Trahisons",
          // "Rituels du Matin en Couple, Répartition des Tâches Domestiques, Vie de Couple et Animaux de Compagnie",
          // "Organisation et Planification, Les Repas en Amoureux, Cultiver l'Humour au Quotidien",
          // "Partage des Loisirs et Passions, Traditions Familiales, Vivre Ensemble : Problèmes et Solutions",
          // "Gestion des Invités et Famille, Concilier Espaces et Temps Personnels, Partager les Responsabilités",
          // "Les Moments de Silence, Habitudes Nocturnes, Entretenir la Flamme au Quotidien",
          // "Moments de Tendresse, Évolution de la Sexualité dans le Couple, Fantasmes Partagés",
          // "Massage et Relaxation, Art de l'Érotisme, Connecter Spirituellement, Gérer les Désirs et Frustrations",
          // "Jeux de Séduction, Éveil des Sens, Amour et Vieillissement",
          // "Partager ses Secrets, Se Redécouvrir en Couple, Toucher et Proximité, Prendre Soin de l'Autre",
          // "Projets et Rêves Communs, Développement Personnel en Couple, Méditation et Yoga à Deux",
          // "Apprendre et Grandir Ensemble, La Lecture en Couple, Les Voyages Transformateurs",
          // "Coaching de Vie pour les Couples, Ateliers et Retraites de Couple, La Résilience en Amour",
          // "Se Réinventer après une Crise, Investir dans l'Avenir Ensemble, Vision Commune du Futur",
          // "Supporter les Ambitions Individuelles, Défis de la Croissance Mutuelle, Apprendre à Compromettre",
          // "Gérer les Relations avec la Belle-Famille, Amitiés de Couple, Vie Sociale et Vie à Deux",
          // "Rencontres entre Couples, Dîner avec des Amis, Rituels Familiaux, Relation avec les Enfants",
          // "Implication dans la Communauté, Traditions Familiales, Créer des Souvenirs en Famille",
          // "Influence des Amis, Vie en Famille Nombreuse, Familles de Cultures Différentes",
          // "Couples et Relations Intergénérationnelles, Impact des Réseaux Sociaux, Achat d'une Maison Ensemble",
          // "Changer de Ville ou Pays, Choix de Carrière en Couple, Décision d'Avoir des Enfants",
          // "Choisir le Nom de Famille, Prendre des Vacances en Famille, Construire un Projet de Vie Commun",
          // "Choix en Matière de Santé, Éducation des Enfants, Décider d'Adopter ou Pas",
          // "Gestion des Crises Financières, Choisir le Moment de se Marier, Les Animaux dans la Vie de Couple",
          // "Planifier sa Retraite à Deux, Décisions Importantes en Crise, Amours Légendaires de l'Histoire",
          // "Philosophie de l'Amour, Mythes et Légendes Romantiques, Psychologie de l'Amour",
          // "L'Amour dans la Littérature Classique, Influences Culturelles sur l'Amour, Les Grands Penseurs de l'Amour",
          // "Symbolisme de l'Amour dans l'Art, La Société et l'Amour, Amour et Religion",
          // "Poésie Romantique à Travers les Âges, Amour et Politique, Evolution du Mariage",
          // "La Monogamie et les Alternatives, Les Contes d'Amour Universels",
          // "Amour et Technologie, L'Amour à l'Ére Numérique, Rencontres en Ligne, Applications de Rencontre",
          // "Amour à Distance, Relations Virtuelles, Sécurité et Confidentialité en Ligne",
          // "Changements de Vie et Amour, Réaction aux Événements Mondiaux, Impact de la Technologie sur les Relations",
          // "Rituels Culturels en Amour, Pratiques Amoureuses Uniques à Travers le Monde, Influence des Coutumes sur les Relations",
          // "Amour et Gestion du Temps, Équilibrer Travail, Vie Sociale et Vie de Couple",
          // "Changements et Adaptation, Comment les Couples Évoluent avec le Temps, Adaptation aux Changements de Vie",
          "Premières Rencontres, Moments Romantiques Mémorables, Idées de Rendez-vous Créatifs",
          "Romances Littéraires, Amour au Cinéma, Symboles Romantiques, Cadeaux de l'Amour",
          "Secrets d'un Amour Éternel, Lettres d'Amour Épiques, Musique de Romance",
          "Célébrations Romantiques du Monde, Gestes Romantiques Inattendus, Traditions de Mariage Uniques",
          "Les Grands Romantiques de l'Histoire, Langage de l'Amour, Techniques de Communication Positive",
          "Les 5 Langages de l'Amour, Conflits et Résolution, Jeux de Communication, Écoute Active en Couple",
          "Comprendre les Signaux Non-Verbaux, Empathie et Complicité, Comment Exprimer ses Sentiments",
          "Secrets de la Communication Émotionnelle, Valeurs Communes et Divergences, Les Questions Importantes à Poser",
          "Décryptage des Gestes d'Affection, Thérapie de Couple, Différences Culturelles et Communication",
          "Gérer la Distance et l'Éloignement, Les Épreuves de la Vie à Deux, Défis de la Vie Moderne",
          "Rebondir Après une Dispute, Les Défis de la Parentalité, Se Soutenir en Temps de Crise",
          "Inquiétudes et Jalousie, Intimité et Stress, Vie de Couple pendant la Pandémie",
          "Les Secrets de la Patience, Dépendance et Indépendance, Surmonter les Trahisons",
          "Rituels du Matin en Couple, Répartition des Tâches Domestiques, Vie de Couple et Animaux de Compagnie",
          "Organisation et Planification, Les Repas en Amoureux, Cultiver l'Humour au Quotidien",
          "Partage des Loisirs et Passions, Traditions Familiales, Vivre Ensemble : Problèmes et Solutions",
          "Les Moments de Silence, Habitudes Nocturnes, Entretenir la Flamme au Quotidien",
          "Moments de Tendresse, Évolution de la Sexualité dans le Couple, Fantasmes Partagés",
          "Massage et Relaxation, Art de l'Érotisme, Connecter Spirituellement, Gérer les Désirs et Frustrations",
          "Jeux de Séduction, Éveil des Sens, Amour et Vieillissement",
          "Partager ses Secrets, Se Redécouvrir en Couple, Toucher et Proximité, Prendre Soin de l'Autre",
          "Projets et Rêves Communs, Développement Personnel en Couple, Méditation et Yoga à Deux",
          "Apprendre et Grandir Ensemble, La Lecture en Couple, Les Voyages Transformateurs",
          "Coaching de Vie pour les Couples, Ateliers et Retraites de Couple, La Résilience en Amour",
          "Se Réinventer après une Crise, Investir dans l'Avenir Ensemble, Vision Commune du Futur",
          "Supporter les Ambitions Individuelles, Défis de la Croissance Mutuelle, Apprendre à Compromettre",
          "Rencontres entre Couples, Dîner avec des Amis, Rituels Familiaux, Relation avec les Enfants",
          "Implication dans la Communauté, Traditions Familiales, Créer des Souvenirs en Famille",
          "Influence des Amis, Vie en Famille Nombreuse, Familles de Cultures Différentes",
          "Couples et Relations Intergénérationnelles, Impact des Réseaux Sociaux, Achat d'une Maison Ensemble",
          "Changer de Ville ou Pays, Choix de Carrière en Couple, Décision d'Avoir des Enfants",
          "Choisir le Nom de Famille, Prendre des Vacances en Famille, Construire un Projet de Vie Commun",
          "Choix en Matière de Santé, Éducation des Enfants, Décider d'Adopter ou Pas",
          "Gestion des Crises Financières, Choisir le Moment de se Marier, Les Animaux dans la Vie de Couple",
          "Planifier sa Retraite à Deux, Décisions Importantes en Crise, Amours Légendaires de l'Histoire",
          "Philosophie de l'Amour, Mythes et Légendes Romantiques, Psychologie de l'Amour",
          "L'Amour dans la Littérature Classique, Influences Culturelles sur l'Amour, Les Grands Penseurs de l'Amour",
          "Symbolisme de l'Amour dans l'Art, La Société et l'Amour, Amour et Religion",
          "Poésie Romantique à Travers les Âges, Amour et Politique, Evolution du Mariage",
          "La Monogamie et les Alternatives, Les Contes d'Amour Universels",
          "Amour et Technologie, L'Amour à l'Ére Numérique, Rencontres en Ligne, Applications de Rencontre",
          "Amour à Distance, Relations Virtuelles, Sécurité et Confidentialité en Ligne",
          "Changements de Vie et Amour, Réaction aux Événements Mondiaux, Impact de la Technologie sur les Relations",
          "Rituels Culturels en Amour, Pratiques Amoureuses Uniques à Travers le Monde, Influence des Coutumes sur les Relations",
          "Amour et Gestion du Temps, Équilibrer Travail, Vie Sociale et Vie de Couple",
          "Changements et Adaptation, Comment les Couples Évoluent avec le Temps, Adaptation aux Changements de Vie"
        ]
      },
    },    
    {
      "theme": "Statistiques des Pays",
      "category": {
        "name": "Statistiques Globales et Comparatives",
        "subCategory": [
        "Économie et Richesse : Pays Riches, Pays Pauvres, Pays Prospères, Croissance Économique, Hauts Taux d'Impôts, Bas Taux d'Impôts, Niveaux de Vie",
        "Environnement et Pollution : Pays Propres, Pays Pollués, Taux de Pollution Atmosphérique, Taux de Pollution de l'Air, Déforestation, Énergies Renouvelables, Gestion des Déchets",
        "Sécurité et Criminalité : Taux de Criminalité, Taux de Meurtres, Pays Sécurisés, Hauts Taux de Corruption, Bas Taux de Corruption, Indice de Paix Globale, Criminalité Organisée",
        "Éducation et Santé : Meilleures Écoles, Pires Écoles, Meilleurs Systèmes de Santé, Pires Systèmes de Santé, Indice de Développement Humain (IDH), Espérance de Vie, Accès aux Soins de Santé",
        "Urbanisation et Transport : Pays Urbanisés, Réseaux de Transport, Meilleures Routes, Routes Dangereuses, Taux de Propriété Immobilière, Mobilité Urbaine, Accessibilité aux Transports",
        "Technologie et Innovation : Pays Avancés en Technologie, Pays Moins Avancés en Technologie, Meilleurs Systèmes d'Internet, Pires Systèmes d'Internet, Accès à Internet, Innovation Technologique, Industries Innovantes",
        "Tourisme : Pays les Plus Visités, Pays les Moins Visités, Lieux Touristiques Populaires, Tourisme de Masse, Écotourisme, Tourisme Culturel, Pays avec les Meilleures Infrastructures Touristiques",
        "Culture et Société : Pays Connus pour la Sorcellerie, Littérature, Cinéma, Culture Pop, Traditions Culturelles, Festivals Mondiaux, Patrimoine Culturel Immatériel",
        "Démographie et Migration : Taux d'Immigration, Taux de Fécondité, Croissance Démographique, Migration Internationale, Distribution de la Population, Villes les Plus Peuplées, Dynamique de Population",
        "Énergie et Ressources : Pays Producteurs de Pétrole, Consommation Énergétique, Ressources Naturelles, Pays Utilisant les Énergies Renouvelables, Dépendance au Charbon, Énergie Nucléaire, Transition Énergétique",
        "Alimentation et Agriculture : Pays Produisant le Plus de Nourriture, Consommation de Viande, Sécurité Alimentaire, Exportations Agricoles, Consommation d'Eau dans l'Agriculture, Alimentation Durable, Agriculture Biologique",
        "Sports et Loisirs : Pays les Plus Performants aux Jeux Olympiques, Sport National, Pays Passionnés de Football, Événements Sportifs Internationaux, Infrastructures Sportives, Tourisme Sportif, Pratique du Sport",
        "Politique et Gouvernance : Démocraties, Régimes Autoritaires, Systèmes Politiques, Pays avec le Suffrage Universel, Droits des Femmes dans la Politique, Gouvernance Mondiale, Organisations Internationales",
        "Climat et Géographie : Pays avec les Climates les Plus Extrêmes, Zones Désertiques, Pays Montagneux, Pays avec les Côtes les Plus Longues, Risques de Catastrophes Naturelles, Pays Touchés par le Changement Climatique, Îles et Archipels",
        "Industrie et Commerce : Pays Exportateurs, Importateurs, Zones de Libre-échange, Industrie Automobile, Industrie Textile, Commerce de Biens de Consommation, Marchés Émergents",
        "Culture Culinaire : Gastronomie Nationale, Pays avec des Traditions Culinaires Riches, Pays Producteurs de Vins, Pays Célèbres pour le Fromage, Cuisine de Rue, Tourisme Gastronomique, Boissons Nationales"
        ]
    },
  },
]    
